/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Database;

/**
 *
 * @author Citrine
 */
import java.awt.event.WindowEvent;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Dimension;

public class AdminMM extends javax.swing.JFrame {
    
    private int CurPerID = 0;
    
    private void Center() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public AdminMM(int PersID) {
        initComponents();
        Center();
        this.CurPerID = PersID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MMPane1 = new javax.swing.JPanel();
        SupplierInfo = new javax.swing.JButton();
        PointOfSales = new javax.swing.JButton();
        Inventory = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ASMRLogo = new javax.swing.JLabel();
        ASMRSign = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        MMPane2 = new javax.swing.JPanel();
        Personnel = new javax.swing.JButton();
        TransactionHistory = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 756));
        setResizable(false);
        getContentPane().setLayout(null);

        MMPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        MMPane1.setToolTipText("");

        SupplierInfo.setText("Informasi Supplier");
        SupplierInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierInfoActionPerformed(evt);
            }
        });

        PointOfSales.setText("Point of Sales");
        PointOfSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PointOfSalesActionPerformed(evt);
            }
        });

        Inventory.setText("Inventory");
        Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MMPane1Layout = new javax.swing.GroupLayout(MMPane1);
        MMPane1.setLayout(MMPane1Layout);
        MMPane1Layout.setHorizontalGroup(
            MMPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MMPane1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(PointOfSales, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(SupplierInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        MMPane1Layout.setVerticalGroup(
            MMPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MMPane1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(MMPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PointOfSales, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        PointOfSales.getAccessibleContext().setAccessibleName("PointOfSales");

        getContentPane().add(MMPane1);
        MMPane1.setBounds(75, 60, 800, 255);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator1.setMinimumSize(new java.awt.Dimension(7100, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(20000, 2));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 600, 950, 2);

        ASMRLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo2.png"))); // NOI18N
        getContentPane().add(ASMRLogo);
        ASMRLogo.setBounds(30, 624, 236, 121);

        ASMRSign.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        ASMRSign.setText("A.S.M.R Advanced Store Management Repository by Goomers Inc. 1993 TM");
        getContentPane().add(ASMRSign);
        ASMRSign.setBounds(280, 694, 560, 30);

        Title.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Title.setText("Menu Utama");
        getContentPane().add(Title);
        Title.setBounds(396, 15, 152, 34);

        MMPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        MMPane2.setToolTipText("");

        Personnel.setText("Sejarah Transaksi");
        Personnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonnelActionPerformed(evt);
            }
        });

        TransactionHistory.setText("Personalia");
        TransactionHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MMPane2Layout = new javax.swing.GroupLayout(MMPane2);
        MMPane2.setLayout(MMPane2Layout);
        MMPane2Layout.setHorizontalGroup(
            MMPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MMPane2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(TransactionHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(Personnel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        MMPane2Layout.setVerticalGroup(
            MMPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MMPane2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(MMPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Personnel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransactionHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(MMPane2);
        MMPane2.setBounds(75, 321, 800, 255);

        jButton1.setText("Log Out");
        jButton1.setMaximumSize(new java.awt.Dimension(130, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(130, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(740, 20, 130, 30);
        jButton1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SupplierInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierInfoActionPerformed
        this.setVisible(false);
        Supplier Sup = new Supplier(this.CurPerID);
        Sup.setVisible(true);
    }//GEN-LAST:event_SupplierInfoActionPerformed

    private void PointOfSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PointOfSalesActionPerformed
        this.setVisible(false);
        Purchase POS = new Purchase(this.CurPerID);
        POS.setVisible(true);
    }//GEN-LAST:event_PointOfSalesActionPerformed

    private void InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryActionPerformed
        this.setVisible(false);
        Inventory Inv = new Inventory(this.CurPerID);
        Inv.setVisible(true);
    }//GEN-LAST:event_InventoryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        LoginGUI Log = new LoginGUI();
        Log.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TransactionHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionHistoryActionPerformed
        this.setVisible(false);
        PersonellManagement Pers = new PersonellManagement(this.CurPerID);
        Pers.setVisible(true);
    }//GEN-LAST:event_TransactionHistoryActionPerformed

    private void PersonnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonnelActionPerformed
        this.setVisible(false);
        Transactions Trans = new Transactions(this.CurPerID);
        Trans.setVisible(true);
    }//GEN-LAST:event_PersonnelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ASMRLogo;
    private javax.swing.JLabel ASMRSign;
    private javax.swing.JButton Inventory;
    private javax.swing.JPanel MMPane1;
    private javax.swing.JPanel MMPane2;
    private javax.swing.JButton Personnel;
    private javax.swing.JButton PointOfSales;
    private javax.swing.JButton SupplierInfo;
    private javax.swing.JLabel Title;
    private javax.swing.JButton TransactionHistory;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

private void systemExit() {
    WindowEvent WinClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
}

}

