/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Database;

/**
 *
 * @author Citrine
 */
import java.awt.event.WindowEvent;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.sql.SQLException;
import java.awt.Dimension;

public class LoginGUI extends javax.swing.JFrame {
    
    private void Center() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public LoginGUI() {
        initComponents();
        Center();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ASMRLogoBig = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        Password = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ASMRLogo = new javax.swing.JLabel();
        ASMRSign = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 775));
        setResizable(false);
        getContentPane().setLayout(null);

        ASMRLogoBig.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        ASMRLogoBig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ASMRLogoBig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo3.png"))); // NOI18N
        getContentPane().add(ASMRLogoBig);
        ASMRLogoBig.setBounds(145, 11, 658, 198);

        LoginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        LoginPanel.setToolTipText("");
        LoginPanel.setLayout(null);

        Password.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Password.setText("Password");
        LoginPanel.add(Password);
        Password.setBounds(175, 109, 113, 38);

        Username.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Username.setText("Username");
        LoginPanel.add(Username);
        Username.setBounds(175, 37, 113, 38);

        UsernameField.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        UsernameField.setForeground(new java.awt.Color(204, 204, 204));
        UsernameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        UsernameField.setText("Username");
        UsernameField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        UsernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFieldFocusLost(evt);
            }
        });
        LoginPanel.add(UsernameField);
        UsernameField.setBounds(341, 37, 306, 38);

        PasswordField.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(204, 204, 204));
        PasswordField.setText("Password");
        PasswordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusLost(evt);
            }
        });
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        LoginPanel.add(PasswordField);
        PasswordField.setBounds(341, 109, 306, 38);

        Login.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        Login.setText("Login");
        Login.setMaximumSize(new java.awt.Dimension(70, 20));
        Login.setMinimumSize(new java.awt.Dimension(70, 20));
        Login.setPreferredSize(new java.awt.Dimension(220, 31));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        LoginPanel.add(Login);
        Login.setBounds(302, 193, 220, 31);

        getContentPane().add(LoginPanel);
        LoginPanel.setBounds(63, 227, 810, 330);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator1.setMinimumSize(new java.awt.Dimension(7100, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(20000, 2));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(-10, 617, 20000, 2);

        ASMRLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo2.png"))); // NOI18N
        getContentPane().add(ASMRLogo);
        ASMRLogo.setBounds(20, 620, 236, 121);

        ASMRSign.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        ASMRSign.setText("A.S.M.R Advanced Store Management Repository by Goomers Inc. 1993 TM");
        getContentPane().add(ASMRSign);
        ASMRSign.setBounds(270, 690, 560, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String Password = CryptWithMD5.cryptWithMD5(PasswordField.getText());
        
        try {
            boolean loggedin = false;
            String SelStm = "SELECT * FROM Personnel";
            java.sql.Connection conn = Config.ConfigDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(SelStm);
            
            while(res.next()) {
                if(UsernameField.getText().equals(res.getString(8)) && Password.equals(res.getString(9)) &&
                        res.getString(4).equals("not admin")) {
                    this.setVisible(false);
                    UserMM User = new UserMM(res.getInt(1));
                    User.setVisible(true);
                    loggedin = true;
                    break;
                } else if (UsernameField.getText().equals(res.getString(8)) && Password.equals(res.getString(9)) &&
                        res.getString(4).equals("admin")){
                    this.setVisible(false);
                    AdminMM Admin = new AdminMM(res.getInt(1));
                    Admin.setVisible(true);
                    loggedin = true;
                    break;
                } 
            }
            
            if(!loggedin) {
                JOptionPane.showMessageDialog(this, "Error: Username/Password Salah");
            }
            
            
        } catch(SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void PasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusGained
        if(PasswordField.getText().equals("Password")) {
            PasswordField.setText("");
            PasswordField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_PasswordFieldFocusGained

    private void UsernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFieldFocusLost
        if(UsernameField.getText().equals("")) {
            UsernameField.setText("Username");
            UsernameField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_UsernameFieldFocusLost

    private void UsernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFieldFocusGained
        if(UsernameField.getText().equals("Username")) {
            UsernameField.setText("");
            UsernameField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_UsernameFieldFocusGained

    private void PasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusLost
        if(PasswordField.getText().equals("")) {
            PasswordField.setText("Password");
            PasswordField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_PasswordFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ASMRLogo;
    private javax.swing.JLabel ASMRLogoBig;
    private javax.swing.JLabel ASMRSign;
    private javax.swing.JButton Login;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}

