/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Database;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.table.*;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Arrays;
        
/**
 *
 * @author Citrine
 */
public class Supplier extends javax.swing.JFrame {
    
    private int CurPersID = 0;
    boolean AdminPerms = true;

    private Supplier() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void Center() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    private void EmptyForm() {
        PhoneField.setText("Nomor HP");
        NameField.setText("Nama Supplier");
        EmailField.setText("Email");
        IDField.setText("ID Supplier");
        IDField.setForeground(new Color(204, 204, 204));
        NameField.setForeground(new Color(204, 204, 204));
        PhoneField.setForeground(new Color(204, 204, 204));
        EmailField.setForeground(new Color(204, 204, 204));
    }
    
    private void Show_Data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Supplier");
        model.addColumn("Nama Supplier");
        model.addColumn("Nomor HP");
        model.addColumn("Email");
        Table.setModel(model);
        
        try {
            String SelStm = "SELECT * FROM Supplier";
            java.sql.Connection conn = Config.ConfigDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(SelStm);
            
            while(res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2),
                        res.getString(3), res.getString(4)});
            }
            
            Table.setModel(model);
            
        } catch(SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    private void Show_DataStm(String SelStm){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Supplier");
        model.addColumn("Nama Supplier");
        model.addColumn("Nomor HP");
        model.addColumn("Email");
        Table.setModel(model);
        
        try {
            java.sql.Connection conn = Config.ConfigDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(SelStm);
            
            while(res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2),
                        res.getString(3), res.getString(4)});
            }
            
            Table.setModel(model);
            
        } catch(SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    public Supplier(int PersID) {
        initComponents();
        Center();
        Show_Data();
        EmptyForm();
        this.CurPersID = PersID;
    }
    
    public Supplier(boolean Perms, int PersID) {
        initComponents();
        Center();
        Show_Data();
        EmptyForm();
        this.AdminPerms = Perms;
        this.CurPersID = PersID;
        
        if(Perms) {
            
        } else {
            NameField.setFocusable(false);
            EmailField.setFocusable(false);
            PhoneField.setFocusable(false);
            IDField.setFocusable(false);
            AddData.setEnabled(false);
            Delete.setEnabled(false);
            Edit.setEnabled(false);
            Cancel.setEnabled(false);
            NameField.setEnabled(false);
            EmailField.setEnabled(false);
            PhoneField.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SupplierID = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        PhoneNo = new javax.swing.JLabel();
        SupplierName = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        TablePane = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        IDField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        PhoneField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ASMRSign = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        AddData = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        ASMRLogo = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        SearchBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        SupplierID.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        SupplierID.setText("ID Supplier");
        SupplierID.setPreferredSize(new java.awt.Dimension(118, 26));
        getContentPane().add(SupplierID);
        SupplierID.setBounds(80, 80, 155, 26);

        Title.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Title.setText("Supplier");
        getContentPane().add(Title);
        Title.setBounds(380, 20, 180, 34);

        PhoneNo.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        PhoneNo.setText("Nomor HP");
        PhoneNo.setMaximumSize(new java.awt.Dimension(118, 26));
        PhoneNo.setMinimumSize(new java.awt.Dimension(118, 26));
        PhoneNo.setPreferredSize(new java.awt.Dimension(118, 26));
        getContentPane().add(PhoneNo);
        PhoneNo.setBounds(80, 220, 155, 26);

        SupplierName.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        SupplierName.setText("Nama Supplier");
        SupplierName.setMaximumSize(new java.awt.Dimension(118, 26));
        SupplierName.setMinimumSize(new java.awt.Dimension(118, 26));
        SupplierName.setPreferredSize(new java.awt.Dimension(118, 26));
        getContentPane().add(SupplierName);
        SupplierName.setBounds(80, 150, 155, 26);

        Email.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        Email.setText("Email");
        Email.setMaximumSize(new java.awt.Dimension(118, 26));
        Email.setMinimumSize(new java.awt.Dimension(118, 26));
        Email.setPreferredSize(new java.awt.Dimension(118, 26));
        getContentPane().add(Email);
        Email.setBounds(80, 280, 183, 26);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        TablePane.setViewportView(Table);

        getContentPane().add(TablePane);
        TablePane.setBounds(84, 420, 769, 168);

        IDField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        IDField.setForeground(new java.awt.Color(204, 204, 204));
        IDField.setText("ID Supplier");
        IDField.setEnabled(false);
        IDField.setFocusable(false);
        IDField.setMaximumSize(new java.awt.Dimension(125, 26));
        IDField.setMinimumSize(new java.awt.Dimension(125, 26));
        IDField.setPreferredSize(new java.awt.Dimension(125, 26));
        IDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFieldFocusLost(evt);
            }
        });
        getContentPane().add(IDField);
        IDField.setBounds(280, 80, 570, 26);

        NameField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        NameField.setForeground(new java.awt.Color(204, 204, 204));
        NameField.setText("Nama Supplier");
        NameField.setMaximumSize(new java.awt.Dimension(125, 26));
        NameField.setMinimumSize(new java.awt.Dimension(125, 26));
        NameField.setName(""); // NOI18N
        NameField.setPreferredSize(new java.awt.Dimension(125, 26));
        NameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameFieldFocusLost(evt);
            }
        });
        getContentPane().add(NameField);
        NameField.setBounds(280, 150, 570, 26);

        PhoneField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        PhoneField.setForeground(new java.awt.Color(204, 204, 204));
        PhoneField.setText("Nomor HP");
        PhoneField.setMaximumSize(new java.awt.Dimension(125, 26));
        PhoneField.setMinimumSize(new java.awt.Dimension(125, 26));
        PhoneField.setPreferredSize(new java.awt.Dimension(125, 26));
        PhoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PhoneFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PhoneFieldFocusLost(evt);
            }
        });
        getContentPane().add(PhoneField);
        PhoneField.setBounds(280, 220, 570, 26);

        EmailField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        EmailField.setForeground(new java.awt.Color(204, 204, 204));
        EmailField.setText("Email");
        EmailField.setMaximumSize(new java.awt.Dimension(125, 26));
        EmailField.setMinimumSize(new java.awt.Dimension(125, 26));
        EmailField.setPreferredSize(new java.awt.Dimension(125, 26));
        EmailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFieldFocusLost(evt);
            }
        });
        getContentPane().add(EmailField);
        EmailField.setBounds(280, 280, 570, 26);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator1.setPreferredSize(new java.awt.Dimension(20000, 2));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 606, 20000, 2);

        ASMRSign.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        ASMRSign.setText("A.S.M.R Advanced Store Management Repository by Goomers Inc. 1993 TM");
        getContentPane().add(ASMRSign);
        ASMRSign.setBounds(270, 680, 553, 34);

        Cancel.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(280, 360, 110, 29);

        Edit.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit);
        Edit.setBounds(550, 360, 61, 29);

        Delete.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        Delete.setText("Hapus");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(430, 360, 80, 29);

        AddData.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        AddData.setText("Tambah");
        AddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDataActionPerformed(evt);
            }
        });
        getContentPane().add(AddData);
        AddData.setBounds(90, 360, 140, 29);

        Exit.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        Exit.setText("Kembali");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(750, 360, 90, 29);

        ASMRLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo2.png"))); // NOI18N
        getContentPane().add(ASMRLogo);
        ASMRLogo.setBounds(10, 610, 230, 120);

        Search.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        Search.setText("Cari");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(650, 360, 61, 29);

        SearchBox.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        SearchBox.setText("Cari");
        SearchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBoxActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBox);
        SearchBox.setBounds(860, 80, 79, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusGained
        if(IDField.getText().equals("ID Supplier")) {
            IDField.setText("");
            IDField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_IDFieldFocusGained

    private void IDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusLost
        if(IDField.getText().equals("")) {
            IDField.setText("ID Supplier");
            IDField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_IDFieldFocusLost

    private void NameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFieldFocusGained
        if(NameField.getText().equals("Nama Supplier")) {
            NameField.setText("");
            NameField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_NameFieldFocusGained

    private void NameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFieldFocusLost
        if(NameField.getText().equals("")) {
            NameField.setText("Nama Supplier");
            NameField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_NameFieldFocusLost

    private void PhoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneFieldFocusGained
        if(PhoneField.getText().equals("Nomor HP")) {
            PhoneField.setText("");
            PhoneField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_PhoneFieldFocusGained

    private void PhoneFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneFieldFocusLost
        if(PhoneField.getText().equals("")) {
            PhoneField.setText("Nomor HP");
            PhoneField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_PhoneFieldFocusLost

    private void EmailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFieldFocusLost
        if(EmailField.getText().equals("")) {
            EmailField.setText("Email");
            EmailField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_EmailFieldFocusLost

    private void EmailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFieldFocusGained
        if(EmailField.getText().equals("Email")) {
            EmailField.setText("");
            EmailField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_EmailFieldFocusGained

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        if(this.AdminPerms == true) {
            this.setVisible(false);
            AdminMM Admin = new AdminMM(this.CurPersID);
            Admin.setVisible(true);
        } else {
            this.setVisible(false);
            UserMM User = new UserMM(this.CurPersID);
            User.setVisible(true);
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        EmptyForm();
        Show_Data();
    }//GEN-LAST:event_CancelActionPerformed

    private void AddDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDataActionPerformed
        if(NameField.getText().equals("Nama Supplier") ||
                PhoneField.getText().equals("Nomor HP") || EmailField.getText().equals("Email")) {
            
            JOptionPane.showMessageDialog(null, "Please fill in all fields before proceeding");
        } else {
            try {
                String stm = "INSERT INTO Supplier VALUES (NULL, '" +
                    NameField.getText() + "', '" + PhoneField.getText() + "', '" +
                    EmailField.getText() + "');";
                
                java.sql.Connection conn = Config.ConfigDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(stm);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Changes have been saved");
                Show_Data();
                EmptyForm();
            } catch(HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_AddDataActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        int row = Table.rowAtPoint(evt.getPoint());
        IDField.setText(Table.getValueAt(row, 0).toString());
        NameField.setText(Table.getValueAt(row, 1).toString());
        PhoneField.setText(Table.getValueAt(row, 2).toString());
        EmailField.setText(Table.getValueAt(row, 3).toString());
        IDField.setForeground(new Color(0, 0, 0));
        NameField.setForeground(new Color(0, 0, 0));
        PhoneField.setForeground(new Color(0, 0, 0));
        EmailField.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_TableMouseClicked

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        if(IDField.getText().equals("ID Supplier") || NameField.getText().equals("Nama Supplier") ||
                PhoneField.getText().equals("Nomor HP") || EmailField.getText().equals("Email")) {
            
            JOptionPane.showMessageDialog(null, "Please fill in all fields before proceeding");
        } else {
            try {
                String stm = "UPDATE Supplier SET SupplierID='" + IDField.getText() + "', SupplierName='" +
                    NameField.getText() + "', PhoneNo='" + PhoneField.getText() + "', Email='" +
                    EmailField.getText() + "' WHERE SupplierID='" + IDField.getText() + "';";
                
                java.sql.Connection conn = Config.ConfigDB();
                conn.setAutoCommit(false);
                java.sql.PreparedStatement pstm = conn.prepareStatement(stm);
                pstm.execute();
                conn.commit();
                JOptionPane.showMessageDialog(null, "Edit successful");
                Show_Data();
                EmptyForm();
            } catch(HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_EditActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if(IDField.getText().equals("ID Supplier") || NameField.getText().equals("Nama Supplier") ||
                PhoneField.getText().equals("Nomor HP") || EmailField.getText().equals("Email")) {
            
            JOptionPane.showMessageDialog(null, "Please fill in all fields before proceeding");
        } else {
        try {
            String stm = "DELETE FROM Supplier WHERE SupplierID='" + IDField.getText() + "';";
                
            java.sql.Connection conn = Config.ConfigDB();
            conn.setAutoCommit(false);
            java.sql.PreparedStatement pstm = conn.prepareStatement(stm);
            pstm.execute();
            conn.commit();
            JOptionPane.showMessageDialog(null, "Delete successful");
            Show_Data();
            EmptyForm();
            
            } catch(HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

        

    }//GEN-LAST:event_DeleteActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        int FieldsFilled = 0;
        
        List<String> Stms = new ArrayList<>(Arrays.asList("SupplierID LIKE '%"+ IDField.getText() + "%',",
                "SupplierName LIKE '%"+ NameField.getText() + "%',", "PhoneNo LIKE '%"+ PhoneField.getText() + "%',",
                "Email LIKE '%" + EmailField.getText() + "%',"));
        List<String> Checks = List.of("ID Supplier", "Nama Supplier", "Nomor HP", "Email");
        List<javax.swing.JTextField> Fields = List.of(IDField, NameField, PhoneField, EmailField);
        
        for(int i = 0; i < Fields.size(); i++) {
            if(Fields.get(i).getText().equals(Checks.get(i))) {
                Stms.set(i, "");
            } else{
                FieldsFilled++;
            }
        }
        
        if(FieldsFilled <= 0) {
            JOptionPane.showMessageDialog(null, "Please fill in at least one field");
        } else {
            try {
                String stm = "SELECT * FROM Supplier WHERE ";      
                stm = Stms.stream().map((i) -> i).reduce(stm, String::concat);
                stm = stm.substring(0,stm.length() - 1) + ";";

                java.sql.Connection conn = Config.ConfigDB();
                conn.setAutoCommit(false);
                java.sql.PreparedStatement pstm = conn.prepareStatement(stm);
                pstm.execute();
                conn.commit();
                Show_DataStm(stm);
                EmptyForm();
            } catch(HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void SearchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBoxActionPerformed
        if(SearchBox.isSelected() && !this.AdminPerms) {
            IDField.setEnabled(true);
            NameField.setEnabled(true);
            EmailField.setEnabled(true);
            PhoneField.setEnabled(true);
            IDField.setFocusable(true);
            NameField.setFocusable(true);
            EmailField.setFocusable(true);
            PhoneField.setFocusable(true);
        } else if(!SearchBox.isSelected() && !this.AdminPerms){
            IDField.setEnabled(false);
            NameField.setEnabled(false);
            EmailField.setEnabled(false);
            PhoneField.setEnabled(false);
            IDField.setFocusable(false);
            NameField.setFocusable(false);
            EmailField.setFocusable(false);
            PhoneField.setFocusable(false);
        } else if(SearchBox.isSelected() && this.AdminPerms) {
            IDField.setEnabled(true);
            IDField.setFocusable(true);
        } else {
            IDField.setEnabled(false);
            IDField.setFocusable(false);
        }
    }//GEN-LAST:event_SearchBoxActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ASMRLogo;
    private javax.swing.JLabel ASMRSign;
    private javax.swing.JButton AddData;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailField;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField IDField;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JLabel PhoneNo;
    private javax.swing.JButton Search;
    private javax.swing.JCheckBox SearchBox;
    private javax.swing.JLabel SupplierID;
    private javax.swing.JLabel SupplierName;
    private javax.swing.JTable Table;
    private javax.swing.JScrollPane TablePane;
    private javax.swing.JLabel Title;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
